-- function calls
sin a
tan2 x y
print (n + 1) to:debug
fns[i] $box01 -- get function out of array fns
move object1 [10,20,x * 3]

standard()  -- create a standard material
bend angle:45 -- create a bend modifier
box height:20 width:40 -- create a box

sin x + 1
(sin x) + 1
atan2 (y - 1) (z - 1)

foo = standardMaterial twosided:on shininess:34 \ 
diffuseMap:baz \ 
opacityMap:bar \ 
bumpMap:boo

(if a > b then sin else cos) x --conditional function choice

ref = &$foo.pos
$baz.pos = *ref
$baz.pos = $foo.pos
*ref = [10,0,0]
foo (*ref) x y z
&foo
&$box.position.x
&valArray[23]
*r.controller